### ISSUE TITLE
Issue in example 

### ISSUE THREAD

**Issue by nimbit-software** [arlyon/stailwc#1]
Hi there, thanks for the addon i will be testing it but i noticed there is a small error with the node sample there is a " missing after staliwc

`/** @type {import('next').NextConfig} */
const nextConfig = {
  reactStrictMode: true,
  swcMinify: true,
  experimental: {
    swcPlugins: **[["stailwc", {}]],**
  },
  compiler: {
    emotion: true,
  },
};`

**Comment by arlyon** [comment]
Thanks for the heads-up, fixed. I also just released 0.2.1 which handles the css prop correctly so please check that out. Thanks for testing `stailwc`! :tada:
