### ISSUE TITLE
`grid-flow-col` doesn't work as expected

### ISSUE THREAD

**Issue by henninghall** [arlyon/stailwc#29]
Hi, thanks for a great tool. 

I've tried to migrate from twin.macro and noticed an issue with `grid-flow-col`. It doesn't seem to be applied and works differently compared to `twin.macro` and `className`. 

Using styled-components compiler.

Difference: 

<img width="525" alt="Screenshot 2023-02-18 at 21 35 32" src="https://user-images.githubusercontent.com/1652607/219897284-f14741a2-b58a-41ff-bf5c-db9b563e9a18.png">

```jsx
 <div tw="grid grid-cols-3 gap-1">
      <b></b>
      <b>className</b>
      <b>tw (stailwc)</b>
      <div>
        <div>grid grid-cols-3</div>
      </div>
      <div tw="bg-blue-200">
        <div className="grid grid-cols-3">
          <div>A</div>
          <div>B</div>
          <div>C</div>
        </div>
      </div>
      <div tw="bg-red-200">
        <div tw="grid grid-cols-3">
          <div>A</div>
          <div>B</div>
          <div>C</div>
        </div>
      </div>
      <div>
        <div>grid grid-flow-col</div>
      </div>
      <div tw="bg-blue-200">
        <div className="grid grid-flow-col">
          <div>A</div>
          <div>B</div>
          <div>C</div>
        </div>
      </div>
      <div tw="bg-red-200">
        <div tw="grid grid-flow-col">
          <div>A</div>
          <div>B</div>
          <div>C</div>
        </div>
      </div>
    </div>
```

**Comment by arlyon** [comment]
Thanks for the report! I'll have a look today.

**Comment by arlyon** [comment]
Please check out https://www.npmjs.com/package/stailwc/v/0.15.0 which should have much better coverage of the grid APIs (read: all :) )

**Comment by henninghall** [comment]
Thats great! looking forward to the release 🚀

**Comment by henninghall** [comment]
I can confirm that this now works in 0.15.0  🎉
