### ISSUE TITLE
Styles not applied if starting on very first line character

### ISSUE THREAD

**Issue by henninghall** [arlyon/stailwc#30]
Found another difference between className/twin.macro and stailwc.

If the style is starting on the very first character on a new line, it is not being applied. If adding one or more spaces or tabs it works as expected. 

<img width="623" alt="Screenshot 2023-02-20 at 22 37 59" src="https://user-images.githubusercontent.com/1652607/220202799-2b70c00a-4d5d-4fe5-96df-670f5d7de9bd.png">

```jsx
    <div tw="grid grid-cols-2 m-8 border border-black">
      <div
        className="
bg-blue-200"
      >
        className / twin.macro
      </div>
      <div
        tw="
bg-blue-200"
      >
        tw (stailwc)
      </div>
    </div>
```

**Comment by arlyon** [comment]
Nice! I will release a patch version soon. I tend to have format-on-save so haven't hit these edge cases but it makes sense to have the parser support newlines if it is valid jsx

**Comment by arlyon** [comment]
Fix is here. My release process is a bit wacky ATM so I will not do a release just yet. Hoping to fix it later this week.

https://github.com/arlyon/stailwc/commit/8be0b60c9c50df58176b4cdc30f9472cf20b34b9

**Comment by henninghall** [comment]
Awesome thanks!
