### ISSUE TITLE
Project does not build + import ESM instead of require

### ISSUE THREAD

**Issue by stouch** [arlyon/stailwc#43]
I try to install this project (to fix an issue reported by @halfbakedsneed and to fix the `install.js` for import ESM instead of module.exports require) so I wanted to fork+build and release a new vesion. I'm on Ubuntu 23.

When I `~/.cargo/bin/cargo build --release --target wasm32-wasi`, I got plenty of errors. (Cannot contribute to this repo if I can't even build the release, sadly..).

I rewrited the `install.js` because the actual one seems deprecated if our `tailwind.config.js` is written in ESM (`export default` instead of `module.exports`).

So this is what I'v got now in my vite.config.ts (without any `stailwc/install`) : 

```javascript
import tailwindConfig from "./tailwind.config.js";
import resolveConfig from "tailwindcss/resolveConfig";

const stailwc = (
  options: { wasm?: string; strict?: boolean; engine?: string } = {}
): any => {
  const config = resolveConfig(tailwindConfig);
  config.theme.colors = Object.entries(config.theme.colors)
    .flatMap(([k, v]) => {
      if (typeof v === "object") {
        const items = Object.entries(v).map(([k2, v2]) => [
          k + (k2 !== "DEFAULT" ? "-" + k2 : ""),
          v2,
        ]);
        return items;
      } else {
        return [[k, v]];
      }
    })
    .reduce(
      (acc, [k, v]) => ({
        ...acc,
        [k]: v,
      }),
      {}
    );

  return [
    options?.wasm ?? "stailwc",
    {
      config,
      strict: options?.strict ?? false,
      engine: options?.engine ?? "emotion",
    },
  ];
};

export default defineConfig({
  plugins: [
    dts(),
    react({
      plugins: [
        stailwc({
          engine: "styled-components",
        }),
        ["@swc/plugin-styled-components", {}],
      ],
    }),
  ],
```

**Comment by stouch** [comment]
@arlyon Just for the record, this issue seems to me more urgent than the others because if anyone wants to help by contributing it looks like the project does not build anymore. I can't be sure if it's my config though. Thanks!

**Comment by arlyon** [comment]
Sorry for the late replies on these, it's been busy recently. Are you able to include the compiler error when building? You will need the wasm32-wasi target as well as a nightly compiler. Everything else should 'just work'.

**Comment by stouch** [comment]
Yes I followed the `contributing.md` . I noticed that your last merge request tests failed with very similar errors I got.

**Comment by stouch** [comment]
@arlyon Do you know if someone else contributed to this project and could help ? Just wonder if this repo gonna be maintained in the future. Can't build it anymore (https://github.com/arlyon/stailwc/pull/45 same things I got there) 
Thanks!

**Comment by arlyon** [comment]
Just me for now. Long term maintenance  is planned but as with anyone my availability ebbs and flows :)

If you can paste the compiler error I may be able to help you resolve the issue.

**Comment by arlyon** [comment]
All pushed, please check out master and see if that works for you!

**Comment by stouch** [comment]
I got this (ubuntu 23) : 

```
stailwc git:(master) ~/.cargo/bin/rustup target add wasm32-wasi
info: component 'rust-std' for target 'wasm32-wasi' is up to date
➜  stailwc git:(master) ~/.cargo/bin/cargo test                   
   Compiling syn v1.0.109
   Compiling num-traits v0.2.16
   Compiling tailwind-config v0.17.0 (/var/webprojects/stailwc/crates/tailwind-config)
   Compiling num-integer v0.1.45
   Compiling num-bigint v0.4.3
   Compiling proc-macro-error v1.0.4
   Compiling ptr_meta_derive v0.1.4
   Compiling bytecheck_derive v0.6.11
   Compiling rkyv_derive v0.7.42
   Compiling miette-derive v4.7.1
   Compiling getset v0.1.2
   Compiling phf_macros v0.10.0
   Compiling tailwind-parse-macro v0.17.0 (/var/webprojects/stailwc/crates/tailwind-parse-macro)
   Compiling test-case-macros v2.2.2
error[E0635]: unknown feature `extract_if`
 --> crates/tailwind-parse-macro/src/lib.rs:1:12
  |
1 | #![feature(extract_if)]
  |            ^^^^^^^^^^

error[E0599]: no method named `extract_if` found for mutable reference `&mut Vec<syn::Item>` in the current scope
  --> crates/tailwind-parse-macro/src/lib.rs:17:10
   |
17 |         .extract_if(|i| {
   |          ^^^^^^^^^^ method not found in `&mut Vec<syn::Item>`

error[E0599]: no method named `extract_if` found for struct `Vec<Attribute>` in the current scope
  --> crates/tailwind-parse-macro/src/lib.rs:20:22
   |
20 |                     .extract_if(|a| a.path.segments.last().unwrap().ident.to_string().eq("root"))
   |                      ^^^^^^^^^^ method not found in `Vec<Attribute>`

Some errors have detailed explanations: E0599, E0635.
For more information about an error, try `rustc --explain E0599`.
error: could not compile `tailwind-parse-macro` due to 3 previous errors
warning: build failed, waiting for other jobs to finish...
```

**Comment by stouch** [comment]
Everything is now working on Ubuntu 23 (I had an issue with my local rust version I had to delete it using `sudo apt remove rustc`) and now it's good: 
```bash
Finished release [optimized] target(s) in 1m 33s
```

I actually got a lot of warnings in `cargo test --workspace` but build  works.

**Comment by arlyon** [comment]
Yeah, the integration test suite does not have perfect coverage compared to twin.macro where it was inherited from. Some of the tests are invalid (ie features I do not plan on supporting) but many of them are imperfect impls.

It gives us something to work towards though! :)
