### ISSUE TITLE
Is this lib gonna be maintained ?

### ISSUE THREAD

**Issue by stouch** [arlyon/stailwc#47]
Is this lib still a good choice for production-released app ? Because I found few things in my last issues and we noticed that only very few people work on this lib. I can't contribute because i'm not enough familiar with rust, and I just want to ensure is there still anyone working on this lib ?

**Comment by arlyon** [comment]
I do but it is a free-time thing and is not sponsored by my employer. If you are OK with the current test coverage (80% or so), struggling with performance from babel, and willing to accept falling back to normal CSS if needs be then you are welcome to use it.

I can't give any stronger guarantees than than unfortunately as I am stretched quite thin at the minute.
