### ISSUE TITLE
Error in next 14.0.4 with app router

### ISSUE THREAD

**Issue by AH-dark** [arlyon/stailwc#48]
It always report error, see [dev.log](https://github.com/arlyon/stailwc/files/13801397/dev.log)

**Comment by arlyon** [comment]
Please refer to this discussion, css-in-js support in app router is spotty. https://github.com/arlyon/stailwc/discussions/12

**Comment by AH-dark** [comment]
> Please refer to this discussion, css-in-js support in app router is spotty. #12. If you think this is in fact an issue with this plugin let me know and I will reopen

Switched to styled-components and I'm still not getting it working.

**Comment by AH-dark** [comment]
I suspect it may be an incompatibility issue caused by next.js 14 🤔
